spring.application.name=Learning
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.error.include-message=always



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kamkoumsabrine30@gmail.com
spring.mail.password=vkdb wfsz qmpp unbl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true